---
# List of supported operating system families
supported_os_families:
  - family: "Debian"

# List of supported operating systems and their minimum versions
# This is checked as a fallback if the OS family is not found
supported_os:
  - distribution: "Ubuntu"
    min_version: "16.04"
  - distribution: "Debian"
    min_version: "8" 