---
- name: Debug UFW Rules
  hosts: all
  gather_facts: true
  tasks:
    - name: Debug UFW rules
      ansible.builtin.debug:
        msg: |
          Cloudflare enabled: {{ cloudflare_enabled | default(false) }}
          App server: {{ app_server | default('none') }}
          Base rules: {{ base_ufw_rules | to_nice_yaml }}
          Restricted web rules: {{ restricted_web_ufw_rules | to_nice_yaml }}
          Direct web rules: {{ direct_web_ufw_rules | to_nice_yaml }}
          Docker Swarm rules: {{ docker_swarm_ufw_rules | to_nice_yaml }}
          Final UFW rules: {{ ufw_allowed_ports | to_nice_yaml }} 