---
# Main configuration playbook for WinterFlow.io
# This playbook orchestrates all system configuration tasks

- name: Check system requirements
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: check_requirements

- import_playbook: configure_ssh.yml

- import_playbook: configure_ufw.yml

