---
# Role: check_requirements/check_orchestrator
# Purpose: Validate that the target system meets the orchestrator requirements
# Usage: Include this role in playbooks that need orchestrator compatibility validation
#
# Example:
#   roles:
#     - role: check_requirements/check_orchestrator
#     - role: your_actual_role
#
# Variables:
#   orchestrator_type: The selected orchestrator type (can be empty)
#   supported_orchestrator: List of supported orchestrators

# Support Ansible 2.9
- name: Load orchestrator defaults
  include_vars: ../defaults/main.yml

- name: Ensure orchestrator_type is defined (can be empty)
  fail:
    msg: "orchestrator_type variable is not defined. Please specify the orchestrator type or leave empty if not using orchestrator."
  when: orchestrator_type is not defined

- name: Validate orchestrator selection
  fail:
    msg: >
      Selected orchestrator '{{ orchestrator_type }}' is not supported.
      Supported orchestrators: {{ supported_orchestrator | list | join(', ') }}
      Please select one of the supported orchestrators or configure a custom one.
  when:
    - orchestrator_type is defined
    - orchestrator_type | length > 0
    - orchestrator_type not in (supported_orchestrator | list)
