---
- name: Validate required variables
  assert:
    that:
      - app_dir is defined
    fail_msg: >
      Required variables must be defined:
      - app_dir: The directory with the app files

- name: Delete application folder
  file:
    path: "{{ app_dir }}"
    state: absent
  register: delete_result

- name: Show deletion result
  debug:
    msg: "Application deletion completed: {{ app_dir }}"
  when: delete_result is changed

