---
- name: Validate required variables
  assert:
    that:
      - app_dir is defined
    fail_msg: >
      Required variables must be defined:
      - app_dir: The directory with the app files

- name: Check if compose.custom.yml exists
  stat:
    path: "{{ app_dir }}/compose.custom.yml"
  register: custom_compose_file

- name: Check if compose.override.yml exists
  stat:
    path: "{{ app_dir }}/compose.override.yml"
  register: override_compose_file

- name: Run docker compose down with compose.custom.yml and compose.override.yml
  command: docker compose -f compose.custom.yml -f compose.override.yml down --remove-orphans
  args:
    chdir: "{{ app_dir }}"
  register: docker_compose_down_result
  changed_when: docker_compose_down_result.rc == 0
  when: custom_compose_file.stat.exists and override_compose_file.stat.exists

- name: Run docker compose down with compose.custom.yml only
  command: docker compose -f compose.custom.yml down --remove-orphans
  args:
    chdir: "{{ app_dir }}"
  register: docker_compose_down_result
  changed_when: docker_compose_down_result.rc == 0
  when: custom_compose_file.stat.exists and not override_compose_file.stat.exists

- name: Run docker compose down with compose.yml and compose.override.yml
  command: docker compose -f compose.yml -f compose.override.yml down --remove-orphans
  args:
    chdir: "{{ app_dir }}"
  register: docker_compose_down_result
  changed_when: docker_compose_down_result.rc == 0
  when: not custom_compose_file.stat.exists and override_compose_file.stat.exists

- name: Run docker compose down with compose.yml only
  command: docker compose down --remove-orphans
  args:
    chdir: "{{ app_dir }}"
  register: docker_compose_down_result
  changed_when: docker_compose_down_result.rc == 0
  when: not custom_compose_file.stat.exists and not override_compose_file.stat.exists

- name: Get docker compose status
  command: docker compose ps
  args:
    chdir: "{{ app_dir }}"
  register: docker_compose_status
  changed_when: false

- name: Display docker compose status
  debug:
    var: docker_compose_status.stdout_lines
