---
- name: Get applications status
  hosts: localhost
  become: false
  gather_facts: true

  roles:
    - role: check_requirements

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - apps_path is defined
          - orchestrator is defined
          - orchestrator in ['docker_compose']
          - apps_status_output_path is defined
        fail_msg: >
          Required variables must be defined:
          - apps_path: The directory to store the apps files
          - orchestrator: The orchestrator type
          - orchestrator: Must be one of 'docker_compose'
          - apps_status_output_path: The directory to store the apps statuses

  tasks:
    - name: Create status output directory if not exists
      file:
        path: "{{ apps_status_output_path }}"
        state: directory
        mode: '0755'
      register: status_dir_result

    - name: Clean status output directory
      shell: "rm -rf {{ apps_status_output_path }}/*"
      when: status_dir_result.changed == false

    - name: Find all app directories
      find:
        paths: "{{ apps_path }}"
        file_type: directory
      register: app_directories

    - name: Get status for each application
      include_tasks: "{{ playbook_dir }}/{{ orchestrator }}/tasks/get_app_status.yml"
      vars:
        app_dir: "{{ item.path }}"
        status_output_dir: "{{ apps_status_output_path }}"
      loop: "{{ app_directories.files }}"
