---
- name: Restart ingress controller
  hosts: localhost
  become: false
  gather_facts: true

  #  roles:
  #    - role: check_requirements
  #
  #    - role: docker
  #      when: orchestrator == 'docker-compose'
  #
  #    - role: docker_compose
  #      when: orchestrator == 'docker-compose'

  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - apps_path is defined
          - apps_ingress is defined
          - orchestrator is defined
          - orchestrator in ['docker_compose']
        fail_msg: >
          Required variables must be defined:
          - apps_path: The directory to store the apps files
          - apps_ingress: The ingress system to use
          - orchestrator: The orchestrator type
          - orchestrator: Must be one of 'docker-compose'

  tasks:
    - name: Restart ingress controller
      include_tasks: "{{ playbook_dir }}/{{ orchestrator }}/tasks/restart_ingress.yml"
      vars:
        apps_ingress_dir: "{{ apps_ingress_dir }}"
        apps_ingress_mode: "{{ apps_ingress_mode }}"
        apps_ingress: "{{ apps_ingress }}"
