---
# Main tasks file for check_requirements
# Purpose: Centralize all requirement validations in one place
# Usage: Include this role to run all requirement checks
#
# Example:
#   roles:
#     - role: check_requirements
#     - role: your_actual_role

- name: Include root check
  ansible.builtin.include_role:
    name: check_requirements/check_root

- name: Include OS compatibility check
  ansible.builtin.include_role:
    name: check_requirements/check_os

- name: Include disk space check
  ansible.builtin.include_role:
    name: check_requirements/check_disk_space
