---
# Main tasks file for check_requirements
# Purpose: Centralize all requirement validations in one place
# Usage: Include this role to run all requirement checks
#
# Example:
#   roles:
#     - role: check_requirements
#     - role: your_actual_role

- name: Include OS compatibility check
  include_tasks: check_os/tasks/main.yml

- name: Include ingress controller check
  include_tasks: check_ingress/tasks/main.yml
