---
- name: Include Docker role
  import_role:
    name: docker

- name: Verify Docker Compose installation
  command: docker compose version
  register: docker_compose_verify
  changed_when: false
  failed_when: docker_compose_verify.rc != 0

- name: Configure system settings for Docker Compose
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-docker-compose.conf
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'vm.max_map_count', value: '262144' }
