---
- name: Configure Docker Compose (Debian family)
  when: ansible_os_family == "Debian"
  block:
    - name: Check for Docker Compose (plugin)
      command: docker compose version
      register: docker_compose_check
      changed_when: false
      failed_when: false

    - name: Check for Docker Compose (standalone)
      command: docker-compose version
      register: docker_compose_standalone_check
      changed_when: false
      failed_when: false
      when: docker_compose_check.rc != 0

    - name: Verify Docker Compose installation
      fail:
        msg: "Docker Compose is not available. Neither 'docker compose' nor 'docker-compose' commands work."
      when: 
        - docker_compose_check.rc != 0
        - (docker_compose_standalone_check is not defined or docker_compose_standalone_check.rc != 0)

    - name: Configure system settings for Docker Compose
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/99-docker-compose.conf
        reload: yes
      with_items:
        - { name: 'net.ipv4.ip_forward', value: '1' }
        - { name: 'vm.max_map_count', value: '262144' }
      become: true
      ignore_errors: true
      register: sysctl_result

    - name: Display sysctl configuration results
      debug:
        msg: "Sysctl configuration: {{ item.item.name }} = {{ item.item.value }} ({{ 'SUCCESS' if not item.failed else 'FAILED: ' + item.msg }})"
      with_items: "{{ sysctl_result.results }}"
      when: sysctl_result is defined

- name: Unsupported OS family warning
  when: ansible_os_family != "Debian"
  block:
    - name: Display unsupported OS warning
      debug:
        msg: |
          WARNING: Docker Compose role is not supported on {{ ansible_os_family }} systems.
          This role is designed for Debian-based systems only (Ubuntu, Debian, etc.).
          Current system: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }} family)
          Skipping Docker Compose configuration tasks.
