---
# Playbook for basic system configuration
# Usage: ansible-playbook playbooks/system/configuration/set_locale.yml [-e timezone=UTC]

- name: Configure system settings
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Locale settings
    system_locale: en_US.UTF-8
    system_language: en_US.UTF-8
    system_keyboard: us

  roles:
    - role: check_requirements

  tasks:
    - name: Ensure required language packs are installed
      apt:
        name: "{{ language_packages }}"
        state: present
      vars:
        language_packages: "{{ (ansible_distribution == 'Ubuntu') | ternary(['language-pack-en', 'locales'], ['locales', 'locales-all']) }}"
      when: ansible_os_family == "Debian"

    - name: Generate required locales
      locale_gen:
        name: "{{ system_locale }}"
        state: present

    - name: Set system locale
      command: update-locale LANG={{ system_locale }} LC_ALL={{ system_locale }}
      when: ansible_os_family == "Debian"
      changed_when: false
