---
- name: Validate required variables
  assert:
    that:
      - apps_ingress is defined
      - apps_ingress_mode is defined
      - apps_ingress_dir is defined
    fail_msg: >
      Required variables must be defined:
      - apps_ingress: The ingress system to use
      - apps_ingress_mode: The ingress mode (notls, custom)
      - apps_ingress_dir: The directory to store the ingress files

- name: Create ingress directory
  file:
    path: "{{ apps_ingress_dir }}"
    state: directory
    mode: '0755'

- name: Create compose.yml from template
  template:
    src: "../templates/compose.{{ apps_ingress }}.yml.j2"
    dest: "{{ apps_ingress_dir }}/compose.yml"
    mode: '0644'
  when: apps_ingress != "custom"

- name: Run docker compose pull
  command: docker compose pull
  args:
    chdir: "{{ apps_ingress_dir }}"
  register: docker_compose_up_result
  changed_when: docker_compose_up_result.rc == 0

- name: Run docker compose up
  command: docker compose up -d
  args:
    chdir: "{{ apps_ingress_dir }}"
  register: docker_compose_up_result
  changed_when: docker_compose_up_result.rc == 0

- name: Get docker compose status
  command: docker compose ps
  args:
    chdir: "{{ apps_ingress_dir }}"
  register: docker_compose_status
  changed_when: false

- name: Display docker compose status
  debug:
    var: docker_compose_status.stdout_lines