---
- name: Validate required variables
  assert:
    that:
      - apps_ingress_path is defined
    fail_msg: >
      Required variables must be defined:
      - apps_ingress_path: The directory to store the ingress files

- name: Restart docker compose services
  command: docker compose restart
  args:
    chdir: "{{ apps_ingress_path }}"
  register: docker_compose_restart_result
  changed_when: docker_compose_restart_result.rc == 0

- name: Get docker compose status
  command: docker compose ps
  args:
    chdir: "{{ apps_ingress_path }}"
  register: docker_compose_status
  changed_when: false

- name: Display docker compose status
  debug:
    var: docker_compose_status.stdout_lines