---
all:
  vars:
    # Variables
    timezone: UTC
    ssh_login_type: "password"

    # Apps Server
    apps_notifications_email: ""
    apps_ingress: "traefik-notls"
    apps_output_dir: "/opt/winterflow/apps"
    apps_status_output_dir: "/tmp/winterflow/status"

