---
- name: Upgrade system
  hosts: all
  become: true
  gather_facts: true
  vars:
    reboot_if_needed: false

  roles:
    - role: check_requirements

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      register: apt_update
      retries: 3
      delay: 5
      until: apt_update is success

    - name: Upgrade all packages
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
        state: latest
      when: ansible_os_family == "Debian"
      register: apt_upgrade
      retries: 3
      delay: 5
      until: apt_upgrade is success

    - name: Install kernel packages
      apt:
        name: "{{ item }}"
        state: latest
      when: ansible_os_family == "Debian"
      with_items:
        - "{{ 'linux-generic' if ansible_distribution == 'Ubuntu' else 'linux-image-amd64' }}"
      register: kernel_install
      retries: 3
      delay: 5
      until: kernel_install is success

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if reboot is required
      debug:
        msg: >
          System upgrade complete. A reboot is required.
          Please use the system-reboot.yml playbook to perform the reboot.
      when: reboot_required.stat.exists 