---
- name: Configure UFW (Debian family)
  when: ansible_os_family == "Debian"
  become: true
  block:
    # Install UFW package
    - name: Install UFW
      apt:
        name: ufw
        state: present
        update_cache: yes

    # Reset UFW if requested
    - name: Reset UFW to default state
      shell: |
        ufw --force reset
      when: ufw_reset | default(false)

    # Configure default policies
    - name: Set default UFW policies
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      with_items:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }

    # Allow SSH by default to prevent lockout
    - name: Allow SSH
      ufw:
        rule: allow
        port: "{{ ufw_ssh_port }}"
        proto: tcp

    # Configure additional allowed ports
    - name: Configure allowed ports
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto | default('tcp') }}"
        from_ip: "{{ item.from_ip | default(omit) }}"
        comment: "{{ item.comment | default(omit) }}"
      with_items: "{{ ufw_allowed_ports }}"
      when: ufw_allowed_ports is defined

    # Enable UFW
    - name: Enable UFW
      ufw:
        state: enabled

- name: Unsupported OS family warning
  when: ansible_os_family != "Debian"
  block:
    - name: Display unsupported OS warning
      debug:
        msg: |
          WARNING: UFW role is not supported on {{ ansible_os_family }} systems.
          This role is designed for Debian-based systems only (Ubuntu, Debian, etc.).
          Current system: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }} family)
          UFW (Uncomplicated Firewall) is primarily available on Debian-based systems.
          Skipping UFW configuration tasks. 