---
# Role: check_requirements/check_ingress
# Purpose: Validate that the target system meets the ingress controller requirements
# Usage: Include this role in playbooks that need ingress controller compatibility validation
#
# Example:
#   roles:
#     - role: check_requirements/check_ingress
#     - role: your_actual_role
#
# Variables:
#   ingress: The selected ingress controller type (can be empty)
#   supported_ingress: List of supported ingress controllers

# Support Ansible 2.9
- name: Load ingress defaults
  include_vars: ../defaults/main.yml

- name: Ensure ingress is defined (can be empty)
  fail:
    msg: "ingress variable is not defined. Please specify the ingress controller type or leave empty if not using ingress."
  when: ingress is not defined

- name: Validate ingress controller selection
  fail:
    msg: >
      Selected ingress controller '{{ ingress }}' is not supported.
      Supported controllers: {{ supported_ingress | list | join(', ') }}
      Please select one of the supported ingress controllers or configure a custom one.
  when:
    - ingress is defined
    - ingress | length > 0
    - ingress not in (supported_ingress | list)

- name: Check for required ingress controller components
  block:
    - name: Validate traefik-letsencrypt requirements
      fail:
        msg: >
          Required components for traefik-letsencrypt are not available:
          - notifications_email environment variable must be set
          Please ensure all required components are installed and configured.
      when:
        - ingress is defined
        - ingress == 'traefik-letsencrypt'
        - not (lookup('env', 'notifications_email') is defined and lookup('env', 'notifications_email') != '')

    - name: Validate custom ingress configuration
      fail:
        msg: >
          Custom ingress controller requires additional configuration.
          Please ensure you have configured all necessary components for your custom ingress setup.
      when:
        - ingress is defined
        - ingress == 'custom'

    - name: Log ingress controller validation success
      debug:
        msg: "Successfully validated ingress controller configuration for {{ ingress }}"
      when:
        - ingress is defined
        - ingress | length > 0

    - name: Log no ingress controller configured
      debug:
        msg: "No ingress controller configured (ingress is empty)"
      when:
        - ingress is defined
        - ingress | length == 0
  rescue:
    - name: Handle validation errors
      fail:
        msg: "Failed to validate ingress controller configuration: {{ ansible_failed_result.msg }}"
