---
# Role: check_requirements/check_os
# Purpose: Validate that the target system meets the OS requirements
# Usage: Include this role in playbooks that need OS compatibility validation
#
# Example:
#   roles:
#     - role: check_requirements/check_os
#     - role: your_actual_role

- name: Check if system OS family is supported
  set_fact:
    os_family_supported: "{{ ansible_os_family in (supported_os_families | map(attribute='family') | list) }}"

- name: Check if specific OS distribution is supported (fallback)
  set_fact:
    os_distribution_supported: "{{ ansible_distribution in (supported_os | map(attribute='distribution') | list) }}"

- name: Validate OS version if specific distribution is supported
  set_fact:
    os_version_supported: >-
      {{ 
        supported_os | length == 0 or
        (supported_os | selectattr('distribution', 'equalto', ansible_distribution) | list | length == 0) or
        (ansible_distribution_version | string) is version(
          ((supported_os | selectattr('distribution', 'equalto', ansible_distribution) | list | first).min_version | default('0')) | string, 
          '>=', 
          strict=False
        )
      }}

- name: Check if system is supported
  fail:
    msg: >
      This system is not supported. Current system: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }} family).
      {{ supported_os_description }}
  when: not (os_family_supported or (os_distribution_supported and os_version_supported)) 