name: Agent Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Go version from go.mod
        id: goversion
        run: |
          GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+' go.mod | cut -d ' ' -f 2)
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.goversion.outputs.version }}
          check-latest: true

      - name: Generate version
        id: version
        run: |
          echo "version=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Build for linux/amd64
          GOOS=linux GOARCH=amd64 go build -v -o winterflow-agent-linux-amd64 .
          
          # Build for linux/arm64
          GOOS=linux GOARCH=arm64 go build -v -o winterflow-agent-linux-arm64 .

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.version.outputs.version }}" \
            winterflow-agent-linux-* \
            --title "Release v${{ steps.version.outputs.version }}" \
            --draft=false \
            --prerelease=false